# Generated by Django 4.2 on 2023-04-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="staf",
            new_name="staff",
        ),
    ]
