# Generated by Django 4.2 on 2023-04-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atendance", "0002_rename_staf_attendance_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="delta_time",
        ),
    ]
