# Generated by Django 4.2 on 2023-04-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendance", "0003_remove_attendance_delta_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="delta_time",
            field=models.TimeField(default="10:00:00"),
        ),
    ]
