# Generated by Django 4.2 on 2023-04-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendance", "0004_attendance_delta_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="delta_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
