# Generated by Django 4.2 on 2023-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendance", "0005_alter_attendance_delta_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="delta_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
