# Generated by Django 4.2 on 2023-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendance", "0007_alter_attendance_date_alter_attendance_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="delta_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
