# Generated by Django 4.2 on 2023-04-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendance", "0008_attendance_delta_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("kechqoldi", "Kechqoldi"),
                    ("vahtida_kelgan", "Vahtida kelgan"),
                    ("kelmadi", "Kelmadi"),
                ],
                default="kelmadi",
                max_length=100,
            ),
        ),
    ]
