# Generated by Django 4.2 on 2023-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(max_length=122),
        ),
    ]
