# Generated by Django 4.2 on 2023-04-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_event_options_alter_event_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelTable(
            name="event",
            table="event",
        ),
    ]
