# Generated by Django 4.2 on 2023-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("unit_price", models.FloatField()),
                ("total_price", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventories",
                "ordering": ["-created_at"],
            },
        ),
    ]
