# Generated by Django 4.2 on 2023-04-14 21:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("staf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="UZ"
            ),
        ),
    ]
